// This is an Autogenerated code, don't touch!

namespace KrillAudio.Krilloud
{
	public class KL
	{
		public class Tags
		{
			/// <summary>
			/// Tag: button
			/// 2D
			/// </summary>
			public const string button = "button";

			/// <summary>
			/// Tag: dialogue
			/// 2D
			/// </summary>
			public const string dialogue = "dialogue";

			/// <summary>
			/// Tag: environment
			/// 2D
			/// </summary>
			public const string environment = "environment";

			/// <summary>
			/// Tag: music
			/// 2D
			/// </summary>
			public const string music = "music";

			/// <summary>
			/// Tag: player
			/// 2D
			/// </summary>
			public const string player = "player";

			/// <summary>
			/// Tag: reports
			/// 2D
			/// </summary>
			public const string reports = "reports";

		}

		public class Variables
		{
			/// <summary>
			/// Variable: boxstatus
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string boxstatus = "boxstatus";

			/// <summary>
			/// Variable: buttonstatus
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string buttonstatus = "buttonstatus";

			/// <summary>
			/// Variable: notifications
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string notifications = "notifications";

			/// <summary>
			/// Variable: steps
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string steps = "steps";

			/// <summary>
			/// Variable: theme
			/// Range: [0 - 1]
			/// Type: Local
			/// </summary>
			public const string theme = "theme";

		}

		public class Channels
		{
			public const string Atmosphere = "Atmosphere";

			public const string Master = "Master";

			public const string Player = "Player";

			public const string UI = "UI";

		}
	}
}
